# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d51ad5cc052b4a355bf97b9356f56e9b360e115741c9aa5caf4f6356d673e3a0e3999b9e39c61a51f1ee05b738882bff84841aabd95cb3ea728fe1aa184440f4

test:
  secret_key_base: 1cb977f9872af9575f49c9b565eb6d61522696822b438263eb194447d069654db6eae3bed825b699bc22eb83dac6051e02f90360266ca963f7300fb2693a18d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
